config: 
  info: this is config-prod version = 6

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db_cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                              # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
